"""Add monitored_tokens_refs to user table

Revision ID: 4443331faf89
Revises: fb55044fd4a3
Create Date: 2023-11-28 22:31:39.379622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4443331faf89'
down_revision = 'fb55044fd4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitored_tokens_refs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monitored_tokens_refs')

    # ### end Alembic commands ###
