"""Add User, Token and a UserToken join table

Revision ID: 6643f4ad32e8
Revises: 
Create Date: 2023-11-25 00:13:28.499175

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6643f4ad32e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
                    sa.Column('key', sa.String(length=64), nullable=False),
                    sa.Column('attributes', sa.JSON(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key')
                    )
    op.create_table('user',
                    sa.Column('username', sa.String(length=60), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('admin', sa.Boolean(), nullable=True),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('user_token',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('token_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.UniqueConstraint('user_id', 'token_id', name='uq_user_token')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    op.drop_table('user')
    op.drop_table('token')
    # ### end Alembic commands ###
